[package]
name = "disc_fbm_bridge"
version = "0.1.0"
authors = ["enterprisey"]
edition = "2018"

[dependencies]
serenity = "0.8.0"
xdotool = "0.0.2"
ws = "0.9.1"
regex = "1.3.6"
lazy_static = "1.4.0"
config = "0.10.1"
serde = { version = "1.0.105", features = [ "derive" ] }
